version: "3.1"
services:
  web:
    image: odoo:16.0
    container_name: odoo_16
    depends_on:
      - db
    ports:
      - "8069:8069"
    restart: always
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./config_odoo:/etc/odoo
      - ./dev_addons:/mnt/extra-addons
      - ./log:/var/log/odoo
    environment:
      - PASSWORD_FILE=/run/secrets/postgresql_password
      - HOST=db
      - USER=odoo
    secrets:
      - postgresql_password
  db:
    image: postgres:15
    container_name: odoo_db
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-web-data:
  odoo-db-data:
secrets:
  postgresql_password:
    file: odoo_pg_pass
